using System.Collections.Generic;

public static class Constants {
    public static readonly Dictionary<(StatType, decimal), int> StatTypeValue2EquipmentRank =
        new Dictionary<(StatType, decimal), int> {
            { (StatType.Attack, 100), 0 },
            { (StatType.Attack, 120), 1 },
            { (StatType.Attack, 140), 2 },
            { (StatType.Attack, 160), 3 },
            { (StatType.Attack, 180), 4 },
            { (StatType.Attack, 200), 5 },
            { (StatType.Attack, 220), 6 },
            { (StatType.Attack, 240), 7 },
            { (StatType.Attack, 260), 8 },
            { (StatType.Attack, 280), 9 },
            { (StatType.Attack, 300), 10 },
            { (StatType.Attack, 330), 11 },
            { (StatType.Attack, 360), 12 },
            { (StatType.Attack, 390), 13 },
            { (StatType.Attack, 420), 14 },
            { (StatType.Attack, 500), 15 },
            { (StatType.Attack, 525), 15 }, // Reforged
            { (StatType.Attack, 515), 15 }, // 88
            { (StatType.AttackPercent, 0.12m), 0 },
            { (StatType.AttackPercent, 0.14m), 1 },
            { (StatType.AttackPercent, 0.17m), 2 },
            { (StatType.AttackPercent, 0.19m), 3 },
            { (StatType.AttackPercent, 0.22m), 4 },
            { (StatType.AttackPercent, 0.24m), 5 },
            { (StatType.AttackPercent, 0.26m), 6 },
            { (StatType.AttackPercent, 0.29m), 7 },
            { (StatType.AttackPercent, 0.31m), 8 },
            { (StatType.AttackPercent, 0.34m), 9 },
            { (StatType.AttackPercent, 0.36m), 10 },
            { (StatType.AttackPercent, 0.4m), 11 },
            { (StatType.AttackPercent, 0.43m), 12 },
            { (StatType.AttackPercent, 0.47m), 13 },
            { (StatType.AttackPercent, 0.5m), 14 },
            { (StatType.AttackPercent, 0.6m), 15 },
            { (StatType.AttackPercent, 0.65m), 15 }, // Reforged
            { (StatType.Defense, 60), 0 },
            { (StatType.Defense, 72), 1 },
            { (StatType.Defense, 84), 2 },
            { (StatType.Defense, 96), 3 },
            { (StatType.Defense, 108), 4 },
            { (StatType.Defense, 120), 5 },
            { (StatType.Defense, 132), 6 },
            { (StatType.Defense, 144), 7 },
            { (StatType.Defense, 156), 8 },
            { (StatType.Defense, 168), 9 },
            { (StatType.Defense, 180), 10 },
            { (StatType.Defense, 198), 11 },
            { (StatType.Defense, 216), 12 },
            { (StatType.Defense, 234), 13 },
            { (StatType.Defense, 252), 14 },
            { (StatType.Defense, 300), 15 },
            { (StatType.Defense, 310), 15 }, // Reforged, 88
            { (StatType.DefensePercent, 0.12m), 0 },
            { (StatType.DefensePercent, 0.14m), 1 },
            { (StatType.DefensePercent, 0.17m), 2 },
            { (StatType.DefensePercent, 0.19m), 3 },
            { (StatType.DefensePercent, 0.22m), 4 },
            { (StatType.DefensePercent, 0.24m), 5 },
            { (StatType.DefensePercent, 0.26m), 6 },
            { (StatType.DefensePercent, 0.29m), 7 },
            { (StatType.DefensePercent, 0.31m), 8 },
            { (StatType.DefensePercent, 0.34m), 9 },
            { (StatType.DefensePercent, 0.36m), 10 },
            { (StatType.DefensePercent, 0.4m), 11 },
            { (StatType.DefensePercent, 0.43m), 12 },
            { (StatType.DefensePercent, 0.47m), 13 },
            { (StatType.DefensePercent, 0.5m), 14 },
            { (StatType.DefensePercent, 0.6m), 15 },
            { (StatType.DefensePercent, 0.65m), 15 }, // Reforged, 88
            { (StatType.Health, 540), 0 },
            { (StatType.Health, 648), 1 },
            { (StatType.Health, 756), 2 },
            { (StatType.Health, 864), 3 },
            { (StatType.Health, 972), 4 },
            { (StatType.Health, 1080), 5 },
            { (StatType.Health, 1188), 6 },
            { (StatType.Health, 1296), 7 },
            { (StatType.Health, 1404), 8 },
            { (StatType.Health, 1512), 9 },
            { (StatType.Health, 1620), 10 },
            { (StatType.Health, 1782), 11 },
            { (StatType.Health, 1944), 12 },
            { (StatType.Health, 2106), 13 },
            { (StatType.Health, 2268), 14 },
            { (StatType.Health, 2700), 15 },
            { (StatType.Health, 2835), 15 }, // Reforged
            { (StatType.Health, 2765), 15 }, // 88
            { (StatType.HealthPercent, 0.12m), 0 },
            { (StatType.HealthPercent, 0.14m), 1 },
            { (StatType.HealthPercent, 0.17m), 2 },
            { (StatType.HealthPercent, 0.19m), 3 },
            { (StatType.HealthPercent, 0.22m), 4 },
            { (StatType.HealthPercent, 0.24m), 5 },
            { (StatType.HealthPercent, 0.26m), 6 },
            { (StatType.HealthPercent, 0.29m), 7 },
            { (StatType.HealthPercent, 0.31m), 8 },
            { (StatType.HealthPercent, 0.34m), 9 },
            { (StatType.HealthPercent, 0.36m), 10 },
            { (StatType.HealthPercent, 0.4m), 11 },
            { (StatType.HealthPercent, 0.43m), 12 },
            { (StatType.HealthPercent, 0.47m), 13 },
            { (StatType.HealthPercent, 0.5m), 14 },
            { (StatType.HealthPercent, 0.6m), 15 },
            { (StatType.HealthPercent, 0.65m), 15 }, // Reforged, 88
            { (StatType.Speed, 8), 0 },
            { (StatType.Speed, 9), 1 },
            { (StatType.Speed, 11), 2 },
            { (StatType.Speed, 12), 3 },
            { (StatType.Speed, 14), 4 },
            { (StatType.Speed, 16), 5 },
            { (StatType.Speed, 17), 6 },
            { (StatType.Speed, 19), 7 },
            { (StatType.Speed, 20), 8 },
            { (StatType.Speed, 22), 9 },
            { (StatType.Speed, 24), 10 },
            { (StatType.Speed, 26), 11 },
            { (StatType.Speed, 28), 12 },
            { (StatType.Speed, 31), 13 },
            { (StatType.Speed, 33), 14 },
            { (StatType.Speed, 40), 15 },
            { (StatType.Speed, 45), 15 }, // Reforged, 88
            { (StatType.EffectivenessPercent, 0.12m), 0 },
            { (StatType.EffectivenessPercent, 0.14m), 1 },
            { (StatType.EffectivenessPercent, 0.17m), 2 },
            { (StatType.EffectivenessPercent, 0.19m), 3 },
            { (StatType.EffectivenessPercent, 0.22m), 4 },
            { (StatType.EffectivenessPercent, 0.24m), 5 },
            { (StatType.EffectivenessPercent, 0.26m), 6 },
            { (StatType.EffectivenessPercent, 0.29m), 7 },
            { (StatType.EffectivenessPercent, 0.31m), 8 },
            { (StatType.EffectivenessPercent, 0.34m), 9 },
            { (StatType.EffectivenessPercent, 0.36m), 10 },
            { (StatType.EffectivenessPercent, 0.4m), 11 },
            { (StatType.EffectivenessPercent, 0.43m), 12 },
            { (StatType.EffectivenessPercent, 0.47m), 13 },
            { (StatType.EffectivenessPercent, 0.5m), 14 },
            { (StatType.EffectivenessPercent, 0.6m), 15 },
            { (StatType.EffectivenessPercent, 0.65m), 15 }, // Reforged, 88
            { (StatType.EffectResistancePercent, 0.12m), 0 },
            { (StatType.EffectResistancePercent, 0.14m), 1 },
            { (StatType.EffectResistancePercent, 0.17m), 2 },
            { (StatType.EffectResistancePercent, 0.19m), 3 },
            { (StatType.EffectResistancePercent, 0.22m), 4 },
            { (StatType.EffectResistancePercent, 0.24m), 5 },
            { (StatType.EffectResistancePercent, 0.26m), 6 },
            { (StatType.EffectResistancePercent, 0.29m), 7 },
            { (StatType.EffectResistancePercent, 0.31m), 8 },
            { (StatType.EffectResistancePercent, 0.34m), 9 },
            { (StatType.EffectResistancePercent, 0.36m), 10 },
            { (StatType.EffectResistancePercent, 0.4m), 11 },
            { (StatType.EffectResistancePercent, 0.43m), 12 },
            { (StatType.EffectResistancePercent, 0.47m), 13 },
            { (StatType.EffectResistancePercent, 0.5m), 14 },
            { (StatType.EffectResistancePercent, 0.6m), 15 },
            { (StatType.EffectResistancePercent, 0.65m), 15 }, // Reforged, 88
            { (StatType.CriticalHitChancePercent, 0.11m), 0 },
            { (StatType.CriticalHitChancePercent, 0.13m), 1 },
            { (StatType.CriticalHitChancePercent, 0.15m), 2 },
            { (StatType.CriticalHitChancePercent, 0.18m), 3 },
            { (StatType.CriticalHitChancePercent, 0.2m), 4 },
            { (StatType.CriticalHitChancePercent, 0.22m), 5 },
            { (StatType.CriticalHitChancePercent, 0.24m), 6 },
            { (StatType.CriticalHitChancePercent, 0.26m), 7 },
            { (StatType.CriticalHitChancePercent, 0.29m), 8 },
            { (StatType.CriticalHitChancePercent, 0.31m), 9 },
            { (StatType.CriticalHitChancePercent, 0.33m), 10 },
            { (StatType.CriticalHitChancePercent, 0.36m), 11 },
            { (StatType.CriticalHitChancePercent, 0.4m), 12 },
            { (StatType.CriticalHitChancePercent, 0.43m), 13 },
            { (StatType.CriticalHitChancePercent, 0.46m), 14 },
            { (StatType.CriticalHitChancePercent, 0.55m), 15 },
            { (StatType.CriticalHitChancePercent, 0.6m), 15 }, // Reforged, 88
            { (StatType.CriticalHitDamagePercent, 0.13m), 0 },
            { (StatType.CriticalHitDamagePercent, 0.16m), 1 },
            { (StatType.CriticalHitDamagePercent, 0.18m), 2 },
            { (StatType.CriticalHitDamagePercent, 0.21m), 3 },
            { (StatType.CriticalHitDamagePercent, 0.23m), 4 },
            { (StatType.CriticalHitDamagePercent, 0.26m), 5 },
            { (StatType.CriticalHitDamagePercent, 0.29m), 6 },
            { (StatType.CriticalHitDamagePercent, 0.31m), 7 },
            { (StatType.CriticalHitDamagePercent, 0.34m), 8 },
            { (StatType.CriticalHitDamagePercent, 0.36m), 9 },
            { (StatType.CriticalHitDamagePercent, 0.39m), 10 },
            { (StatType.CriticalHitDamagePercent, 0.43m), 11 },
            { (StatType.CriticalHitDamagePercent, 0.47m), 12 },
            { (StatType.CriticalHitDamagePercent, 0.51m), 13 },
            { (StatType.CriticalHitDamagePercent, 0.55m), 14 },
            { (StatType.CriticalHitDamagePercent, 0.65m), 15 },
            { (StatType.CriticalHitDamagePercent, 0.7m), 15 } // Reforged, 88
        };

    // Based on https://github.com/fribbels/Fribbels-Epic-7-Optimizer/blob/main/app/js/lib/reforge.js#L886
    public static readonly Dictionary<StatType, decimal> StatType2GearScoreMultiplier =
        new Dictionary<StatType, decimal> {
            { StatType.Attack, 3.46m / 39 },
            { StatType.AttackPercent, 8m / 8 * 100 },
            { StatType.Defense, 4.99m / 31 },
            { StatType.DefensePercent, 8m / 8 * 100 },
            { StatType.Health, 3.09m / 174 },
            { StatType.HealthPercent, 8m / 8 * 100 },
            { StatType.Speed, 8m / 4 },
            { StatType.EffectivenessPercent, 8m / 8 * 100 },
            { StatType.EffectResistancePercent, 8m / 8 * 100 },
            { StatType.CriticalHitChancePercent, 8m / 5 * 100 },
            { StatType.CriticalHitDamagePercent, 8m / 7 * 100 }
        };
    // Based on https://github.com/fribbels/Fribbels-Epic-7-Optimizer/blob/main/app/js/lib/reforge.js#L915
    public static readonly Dictionary<(StatType, int), decimal> StatTypeRollCount2ReforgedBonusValue =
        new Dictionary<(StatType, int), decimal> {
            { (StatType.Attack, 0), 11 },
            { (StatType.Attack, 1), 11 * 2 },
            { (StatType.Attack, 2), 11 * 3 },
            { (StatType.Attack, 3), 11 * 4 },
            { (StatType.Attack, 4), 11 * 5 },
            { (StatType.Attack, 5), 11 * 6 },
            { (StatType.AttackPercent, 0), 0.01m },
            { (StatType.AttackPercent, 1), 0.03m },
            { (StatType.AttackPercent, 2), 0.04m },
            { (StatType.AttackPercent, 3), 0.05m },
            { (StatType.AttackPercent, 4), 0.07m },
            { (StatType.AttackPercent, 5), 0.08m },
            { (StatType.Defense, 0), 9 },
            { (StatType.Defense, 1), 9 * 2 },
            { (StatType.Defense, 2), 9 * 3 },
            { (StatType.Defense, 3), 9 * 4 },
            { (StatType.Defense, 4), 9 * 5 },
            { (StatType.Defense, 5), 9 * 6 },
            { (StatType.DefensePercent, 0), 0.01m },
            { (StatType.DefensePercent, 1), 0.03m },
            { (StatType.DefensePercent, 2), 0.04m },
            { (StatType.DefensePercent, 3), 0.05m },
            { (StatType.DefensePercent, 4), 0.07m },
            { (StatType.DefensePercent, 5), 0.08m },
            { (StatType.Health, 0), 56 },
            { (StatType.Health, 1), 56 * 2 },
            { (StatType.Health, 2), 56 * 3 },
            { (StatType.Health, 3), 56 * 4 },
            { (StatType.Health, 4), 56 * 5 },
            { (StatType.Health, 5), 56 * 6 },
            { (StatType.HealthPercent, 0), 0.01m },
            { (StatType.HealthPercent, 1), 0.03m },
            { (StatType.HealthPercent, 2), 0.04m },
            { (StatType.HealthPercent, 3), 0.05m },
            { (StatType.HealthPercent, 4), 0.07m },
            { (StatType.HealthPercent, 5), 0.08m },
            { (StatType.Speed, 0), 0 },
            { (StatType.Speed, 1), 1 },
            { (StatType.Speed, 2), 2 },
            { (StatType.Speed, 3), 3 },
            { (StatType.Speed, 4), 4 },
            { (StatType.Speed, 5), 4 },
            { (StatType.EffectivenessPercent, 0), 0.01m },
            { (StatType.EffectivenessPercent, 1), 0.03m },
            { (StatType.EffectivenessPercent, 2), 0.04m },
            { (StatType.EffectivenessPercent, 3), 0.05m },
            { (StatType.EffectivenessPercent, 4), 0.07m },
            { (StatType.EffectivenessPercent, 5), 0.08m },
            { (StatType.EffectResistancePercent, 0), 0.01m },
            { (StatType.EffectResistancePercent, 1), 0.03m },
            { (StatType.EffectResistancePercent, 2), 0.04m },
            { (StatType.EffectResistancePercent, 3), 0.05m },
            { (StatType.EffectResistancePercent, 4), 0.07m },
            { (StatType.EffectResistancePercent, 5), 0.08m },
            { (StatType.CriticalHitChancePercent, 0), 0.01m },
            { (StatType.CriticalHitChancePercent, 1), 0.02m },
            { (StatType.CriticalHitChancePercent, 2), 0.03m },
            { (StatType.CriticalHitChancePercent, 3), 0.04m },
            { (StatType.CriticalHitChancePercent, 4), 0.05m },
            { (StatType.CriticalHitChancePercent, 5), 0.06m },
            { (StatType.CriticalHitDamagePercent, 0), 0.01m },
            { (StatType.CriticalHitDamagePercent, 1), 0.02m },
            { (StatType.CriticalHitDamagePercent, 2), 0.03m },
            { (StatType.CriticalHitDamagePercent, 3), 0.04m },
            { (StatType.CriticalHitDamagePercent, 4), 0.06m },
            { (StatType.CriticalHitDamagePercent, 5), 0.07m },
        };

    // Based on https://docs.google.com/spreadsheets/d/10n16n7iYPPnWAGrl00j2j0OAjlwQ5MPuGMSd_tTuoNc/edit?gid=49811653#gid=49811653
    public static readonly Dictionary<int, (decimal Min, decimal Max)> EquipmentRank2GearScoreMinMax =
        new Dictionary<int, (decimal Min, decimal Max)> {
            { 0, (23, 25) }, { 1, (23, 25) }, { 2, (23, 25) },
            { 3, (30, 32) }, { 4, (30, 32) }, { 5, (30, 32) },
            { 6, (37, 39) }, { 7, (37, 39) }, { 8, (37, 39) },
            { 9, (44, 46) }, { 10, (44, 46) }, { 11, (44, 46) },
            { 12, (52, 53) }, { 13, (52, 53) }, { 14, (52, 53) },
            { 15, (60, 60) }
        };
}